# Generated by Django 4.0.4 on 2022-07-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveField(
            model_name="category",
            name="polymorphic_ctype",
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
