# Generated by Django 4.0.4 on 2022-07-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=None, upload_to="images/"),
            preserve_default=False,
        ),
    ]
