# Generated by Django 4.0.4 on 2022-07-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('ELECTRONICS', 'Electronics'), ('BOOK', 'Book')], max_length=100),
        ),
    ]
